# Generated by Django 4.2.1 on 2023-05-30 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0002_alter_category_image"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.category",
            ),
        ),
    ]
