# Generated by Django 4.2.2 on 2023-06-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_products_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="price",
            field=models.FloatField(default=0, null=True),
        ),
    ]
